name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build with Vite
      run: npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: NagiyuClient
        path: home/web/wwwroot/js/dist

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Publish with dotnet
      run: dotnet publish --configuration Release home/web/Nagiyu.Web.csproj

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Nagiyu
        path: home/web/bin/Release/net8.0/publish
